spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/project
        username: postgres
        password: password

    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

    thymeleaf:
        mode: HTML5
        enabled: false

    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
